variables:
  RELEASE: "1"
  BUILD_REQUIRES: {{build_requires}}


stages:
  - Trigger
  - Build
  - PublishRPM


trigger_pipeline:
  type: Trigger
  script:
    - echo "Triggered"
  when: manual
  tags: [cinode]
  allow_failure: false


build_rpm:
  image: docker.maxiv.lu.se/centos7-build:latest
  type:  Build
  script:
    - sudo yum install $BUILD_REQUIRES -y
    - rm ./*.*.rpm -f
    - fpm -s python -t rpm --rpm-dist el7 --verbose --iteration "${RELEASE}" .
  artifacts:
    paths:
      - ./*.rpm
    expire_in: 1 week
  tags: [docker]
  dependencies:
    - trigger_pipeline


testing_el7_x86_64:
  type: PublishRPM
  script:
    - scp -v *.rpm jenkins@srv-repo-0:/repo/testing/el7/x86_64/
    - ssh jenkins@srv-repo-0 createrepo --update /repo/testing/el7/x86_64
  tags: [cinode-0]
  dependencies:
    - build_rpm
  only:
    - develop

public_el7_x86_64:
  type: PublishRPM
  script:
    - scp -v *.rpm jenkins@srv-repo-0:/repo/public/el7/x86_64/
    - ssh jenkins@srv-repo-0 createrepo --update /repo/public/el7/x86_64
  tags: [cinode-0]
  dependencies:
    - build_rpm
  only:
    - master
    
